services:
  clubroomie_backend:
    image: nwplus/clubroomie-api
    build: .
    ports:
      - 4303:4000 # host:container
    volumes:
      - ./serviceAccount.json:/app/serviceAccount.json:ro
      - ./.env:/app/.env:ro
