# Archived: For custom deployment
services:
  clubroomie-api:
    image: nwplus/clubroomie-api
    build: .
    ports:
      - 4303:4303 # host:container
    volumes:
      - ./serviceAccount.json:/app/serviceAccount.json:ro
      - ./.env:/app/.env:ro
