name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main, dev]
    paths:
      - "client/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IS_PRODUCTION: ${{ endsWith(github.ref, 'main') }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Set up firebase
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Load .env.production
        if: ${{ env.IS_PRODUCTION == 'true' }}
        run: cp .env.production .env

      - name: Load .env.development
        if: ${{ env.IS_PRODUCTION == 'false' }}
        run: cp .env.development .env

      - name: Build project
        run: yarn build

      - name: Deploy to dev firebase project
        if: ${{ env.IS_PRODUCTION == 'false' }}
        run: firebase deploy --only hosting:clubroomie-dev --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to prod firebase project
        if: ${{ env.IS_PRODUCTION == 'true' }}
        run: firebase deploy --only hosting:clubroomie --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
