name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main, dev]
    paths:
      - "client/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IS_PRODUCTION: ${{ endsWith(github.ref, 'main') }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Set up firebase
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with dev env variables
        if: ${{ env.IS_PRODUCTION == 'false' }}
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.DEV_FIREBASE_DATABASE_URL }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.DEV_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}
        run: yarn build

      - name: Build with prod env variables
        if: ${{ env.IS_PRODUCTION == 'true' }}
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: yarn build

      - name: Deploy to dev firebase project
        if: ${{ env.IS_PRODUCTION == 'false' }}
        run: firebase deploy --only hosting:clubroomie-dev --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to prod firebase project
        if: ${{ env.IS_PRODUCTION == 'true' }}
        run: firebase deploy --only hosting:clubroomie --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
