name: Dockerize and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: nwplus/clubroomie-api:latest
      - name: Upload systemd service file
        uses: actions/upload-artifact@v4
        with:
          name: clubroomie-service-file
          path: server/clubroomie.service
      - name: Upload docker-compose file
        uses: actions/upload-artifact@v4
        with:
          name: clubroomie-docker-compose
          path: server/docker-compose.yml

  deploy:
    runs-on: self-hosted
    needs: dockerize

    steps:
      - name: Pull Docker image
        run: docker pull nwplus/clubroomie-api:latest

      - name: Download systemd service file
        uses: actions/download-artifact@v4
        with:
          name: clubroomie-service-file
          path: .

      - name: Download docker-compose file
        uses: actions/download-artifact@v4
        with:
          name: clubroomie-docker-compose
          path: .

      - name: Copy systemd service file
        run: sudo cp clubroomie.service /etc/systemd/system/clubroomie.service

      - name: Create .env file from secret
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Create serviceAccount.json file from secret
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > serviceAccount.json

      - name: Reload systemd daemon
        run: sudo systemctl daemon-reload

      - name: Stop existing Clubroomie service
        run: sudo systemctl stop clubroomie

      - name: Enable and start Clubroomie service
        run: |
          sudo systemctl enable clubroomie
          sudo systemctl start clubroomie
